type: regex
pattern: 'host=(?P<host>[^\s]+).*?(?:server|dst)=(?P<dst>[0-9a-fA-F\.:]+)'
fields:
  fqdn: '{host}'
  ip: '{dst}'
timestamp:
  regex: '(?P<ts>\\d{2}/[A-Za-z]{3}/\\d{4}:\\d{2}:\\d{2}:\\d{2} [+-]\\d{4})'
  strptime: '%d/%b/%Y:%H:%M:%S %z'
idn_normalize: true
