name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Lint with Ruff
        run: ruff check .

      - name: Run pytest
        run: pytest
