name: DNS Hygiene Guard (Scheduled)

on:
  schedule:
    - cron: "30 2 * * *"  # 11:30 JST
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  run-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Execute DNS Hygiene Guard (demo data)
        run: python -m dns_hygiene_guard --demo
